import {
  pgTable,
  uuid,
  text,
  integer,
  boolean,
  timestamp,
  pgEnum,
  jsonb,
  real,
} from "drizzle-orm/pg-core";
import { users } from "./users";
import { customType } from "drizzle-orm/pg-core";


export const wallpaperStatusEnum = pgEnum("wallpaper_status", [
  "pending",
  "approved",
  "rejected",
]);

export const wallpaperFormatEnum = pgEnum("wallpaper_format", [
  "jpeg",
  "png",
  "webp",
  "avif",
]);

// define vector type for pgvector
const vector = (name: string, dimensions: number) =>
  customType<{ data: number[] }>({
    dataType() {
      return `vector(${dimensions})`;
    },
    toDriver(value: number[]): string {
      return `[${value.join(",")}]`;
    },
    fromDriver(value: unknown): number[] {
      if (typeof value === "string") {
        return value
          .replace("[", "")
          .replace("]", "")
          .split(",")
          .map(Number);
      }
      return value as number[];
    },
  })(name, {});

export const categories = pgTable("categories", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  description: text("description"),
  coverImageUrl: text("cover_image_url"),
  sortOrder: integer("sort_order").notNull().default(0),
});

export const wallpapers = pgTable("wallpapers", {
  id: uuid("id").primaryKey().defaultRandom(),
  title: text("title").notNull(),
  description: text("description"),
  fileUrl: text("file_url").notNull(),
  cdnVariants: jsonb("cdn_variants"),
  blurhash: text("blurhash").notNull(),
  dominantColor: text("dominant_color").notNull(),
  palette: text("palette").array().notNull().default([]),
  width: integer("width").notNull(),
  height: integer("height").notNull(),
  fileSizeBytes: integer("file_size_bytes").notNull(),
  format: wallpaperFormatEnum("format").notNull(),
  categoryId: uuid("category_id").references(() => categories.id),
  uploaderId: uuid("uploader_id").references(() => users.id),
  tags: text("tags").array().notNull().default([]),
  isPremium: boolean("is_premium").notNull().default(false),
  isFeatured: boolean("is_featured").notNull().default(false),
  isAiGenerated: boolean("is_ai_generated").notNull().default(false),
  downloadCount: integer("download_count").notNull().default(0),
  likeCount: integer("like_count").notNull().default(0),
  viewCount: integer("view_count").notNull().default(0),
  trendingScore: real("trending_score").notNull().default(0),
  status: wallpaperStatusEnum("status").notNull().default("pending"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  /** CLIP visual embedding — for /:id/similar visual similarity (generated by @xenova at upload) */
  embedding: vector("embedding", 512),
  /** OpenAI text-embedding-3-small on title+description+tags — for /search semantic search */
  textEmbedding: vector("text_embedding", 512),
});